config/routes.rb
Rails.application.routes.draw do
  resources :payment_requests, only: %i(index new create)

  root "payment_requests#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/payment_request.rb
# frozen_string_literal: true

class PaymentRequest < ApplicationRecord
  validates :amount, presence: true
  validates :currency, presence: true
  validates :description, presence: true
  validates_numericality_of :amount, greater_than: 0
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/payment_requests_controller.rb
# frozen_string_literal: true

class PaymentRequestsController < ApplicationController
  def index
    @payment_requests = PaymentRequest.all.order(:id)
  end

  def new
    @payment_request = PaymentRequest.new
  end

  def create
    payment_request = PaymentRequest.create!(payment_request_params)
    EmitCreatedPaymentRequestEvent.call(payment_request)
    redirect_to root_path, notice: "Payment request has been created"
  rescue ActiveRecord::ActiveRecordError => e
    flash[:alert] = e.message
    @payment_request = PaymentRequest.new
    render :new
  end

  private

  def payment_request_params
    params.require(:payment_request).permit(:amount, :currency, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/payment_requests/index.html.erb
<table>
  <tr>
    <th>Description</th>
    <th>Amount</th>
    <th>Currency</th>
    <th>Status</th>
  </tr>
  <% @payment_requests.each do |payment_request| %>
    <tr>
      <td><%= payment_request.description %></td>
      <td><%= payment_request.amount %></td>
      <td><%= payment_request.currency %></td>
      <td><%= payment_request.status %></td>
    </tr>
  <% end %>
</table>
<%= link_to "New payment request", new_payment_request_path %>

app/views/payment_requests/new.html.erb
<%= form_for @payment_request do |form| %>
  <%= form.label :description %>
  <%= form.text_field :description %>
  <%= form.label :amount %>
  <%= form.number_field :amount %>
  <%= form.label :currency %>
  <%= form.text_field :currency %>
  <%= form.submit %>
<% end %>